-- Workflows bookkeeping on `export_runs`
--
-- The publish pipeline now runs as a Cloudflare Workflow -- a durable
-- background job that survives Worker restarts, retries failed steps,
-- and can be resumed from the last checkpoint rather than starting
-- over. This migration wires the existing `export_runs` table into
-- that runtime by adding the workflow instance identifier and three
-- timestamp columns the dashboard uses to show mid-run progress: when
-- the current step started, when it finished, and when the workflow
-- last reported a heartbeat.
--
-- Hand-rolled (not generated by drizzle-kit) to keep the migration
-- surgical -- only the four additive columns, no schema churn.
--
-- Version: v0.3.0

ALTER TABLE export_runs ADD COLUMN workflow_instance_id text;--> statement-breakpoint
ALTER TABLE export_runs ADD COLUMN current_step_started_at integer;--> statement-breakpoint
ALTER TABLE export_runs ADD COLUMN current_step_completed_at integer;--> statement-breakpoint
ALTER TABLE export_runs ADD COLUMN last_heartbeat_at integer;
