/**
 * Cloudflare Worker environment bindings.
 *
 * worker-configuration.d.ts (generated by `wrangler types`) is gitignored,
 * so CI needs this file for typecheck to pass. Keep in sync with wrangler.jsonc.
 */
interface Env {
  DB: D1Database;
  BUCKET: R2Bucket;
  APP_NAME: string;
  SENDER_EMAIL: string;
  ALLOWED_MANIFEST_HOSTS: string;
  SESSION_SECRET: string;
  RESEND_API_KEY: string;
  GITHUB_CLIENT_ID?: string;
  GITHUB_CLIENT_SECRET?: string;
}
