import * as fs from "node:fs/promises";
import * as crypto from "node:crypto";
import type { ImportResult } from "../lib/types";
import { escapeSql, generateInserts, writeSqlFiles } from "../lib/sql";

/**
 * Shape of each entity in the entity data export.
 * Only the fields relevant to vocabulary migration are required.
 */
interface EntityRecord {
  id: string;
  primary_function: string | null;
}

/**
 * Migrate entity primaryFunction values to vocabulary_terms references.
 *
 * Reads the vocabulary-term-lookup.json (generated by importVocabularyTerms)
 * and an entity data export JSON. For each entity with a non-null
 * primaryFunction, looks up the vocabulary term UUID via case-insensitive
 * matching. Unmatched values create new "proposed" vocabulary terms.
 *
 * Generates batched SQL:
 *   1. INSERT statements for new "proposed" vocabulary terms
 *   2. UPDATE statements setting primary_function_id on entities
 */
export async function migrateEntityFunctions(
  lookupPath: string,
  entitiesPath: string,
  outputDir = ".import"
): Promise<ImportResult> {
  const lookupRaw = await fs.readFile(lookupPath, "utf8");
  const lookupMap = JSON.parse(lookupRaw) as Record<string, string | null>;

  const entitiesRaw = await fs.readFile(entitiesPath, "utf8");
  const entities = JSON.parse(entitiesRaw) as EntityRecord[];

  const now = Math.floor(Date.now() / 1000);

  // Track new proposed terms to avoid duplicates within this migration
  const proposedTerms = new Map<string, { id: string; canonical: string }>();

  // Collect UPDATE statements as raw SQL strings
  const updateStatements: string[] = [];

  let matched = 0;
  let unmatched = 0;
  let skipped = 0;

  for (const entity of entities) {
    if (!entity.primary_function) {
      skipped++;
      continue;
    }

    const lowerFunction = entity.primary_function.toLowerCase();
    const termId = lookupMap[lowerFunction];

    if (termId) {
      // Found in lookup map — direct match
      updateStatements.push(
        `UPDATE entities SET primary_function_id = ${escapeSql(termId)} WHERE id = ${escapeSql(entity.id)};`
      );
      matched++;
    } else if (termId === null) {
      // Null-canonical entry (compound function) — skip linking but don't create proposed
      skipped++;
    } else {
      // Not in lookup map at all — create a new proposed vocabulary term
      let proposed = proposedTerms.get(lowerFunction);
      if (!proposed) {
        proposed = {
          id: crypto.randomUUID(),
          canonical: entity.primary_function,
        };
        proposedTerms.set(lowerFunction, proposed);
      }
      updateStatements.push(
        `UPDATE entities SET primary_function_id = ${escapeSql(proposed.id)} WHERE id = ${escapeSql(entity.id)};`
      );
      unmatched++;
    }
  }

  // Build all SQL statements in order:
  // 1. INSERT proposed vocabulary terms
  const allStatements: string[] = [];

  if (proposedTerms.size > 0) {
    const termColumns = [
      "id", "canonical", "category", "status", "entity_count",
      "notes", "created_at", "updated_at",
    ];
    const termRows: string[][] = [];
    for (const term of proposedTerms.values()) {
      termRows.push([
        escapeSql(term.id),
        escapeSql(term.canonical),
        escapeSql(null), // category unknown
        escapeSql("proposed"),
        escapeSql(0),
        escapeSql("Auto-created during entity migration — needs review"),
        escapeSql(now),
        escapeSql(now),
      ]);
    }
    const insertStatements = generateInserts("vocabulary_terms", termColumns, termRows, 100);
    allStatements.push(...insertStatements);
  }

  // 2. Batch UPDATE statements in groups of 100
  for (let i = 0; i < updateStatements.length; i += 100) {
    const batch = updateStatements.slice(i, i + 100);
    allStatements.push(batch.join("\n"));
  }

  const sqlFiles = await writeSqlFiles("vocabulary-migration", allStatements, 50, outputDir);

  return {
    table: "vocabulary-migration",
    total: entities.length,
    imported: matched + unmatched,
    skipped,
    errors: [],
    sqlFiles,
  };
}
